Some tweaks

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -15,6 +15,17 @@ if [ -f $ENV_DIR/PROJECT_PATH ]; then
 		TMP_DIR=`mktemp -d $CACHE_DIR/subdirXXXXX`
 		echo "       created tmp dir: $TMP_DIR"
 
+		echo "       moving files to root from MANIFEST_MV_TO_ROOT"
+		for file in $(<$BUILD_DIR/$PROJECT_PATH/MANIFEST_MV_TO_ROOT)
+		do
+			if [ -a $TMP_DIR/$file ]; then
+				mv "$BUILD_DIR/$file" $TMP_DIR/$(basename $file)
+			else
+				echo "File or directory not found: $TMP_DIR/$file"
+				exit 1
+			fi
+		done		
+		
 		echo "       copying required files from MANIFEST_GLOBAL"
 		for file in $(<$BUILD_DIR/$PROJECT_PATH/MANIFEST_GLOBAL)
 		do
@@ -25,17 +36,6 @@ if [ -f $ENV_DIR/PROJECT_PATH ]; then
 				exit 1
 			fi
 		done
-
-		echo "       moving files to root from MANIFEST_MV_TO_ROOT"
-		for file in $(<$BUILD_DIR/$PROJECT_PATH/MANIFEST_MV_TO_ROOT)
-		do
-			if [ -a $TMP_DIR/$file ]; then
-				mv "$TMP_DIR/$file" $TMP_DIR/$(basename $file)
-			else
-				echo "File or directory not found: $TMP_DIR/$file"
-				exit 1
-			fi
-		done		
 
 	 	echo "       cleaning build dir $BUILD_DIR"
 		rm -rf $BUILD_DIR
